server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=Huy24092005@

spring.jpa.hibernate.ddl-auto=update

message=Running Production Environment - PostgreSQL